#!/usr/bin/env bash
# Generates /Applications/Emacsclient.app, a launcher that opens a GUI frame on
# the running Emacs daemon. It exists so the daemon is reachable from Spotlight,
# the Dock and Aerospace without a terminal.
#
# "open -a Emacs" deliberately does not do this: it starts a second, independent
# Emacs. The bundle also refuses to spawn a daemon of its own, because one
# started outside launchd could not be managed by emacsctl afterwards. When the
# job is down it is kickstarted through launchd instead.
set -e

APP="/Applications/Emacsclient.app"
EMACS_APP="/Applications/Emacs.app"
LABEL="dev.nathantebbs.emacs"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

case "$OSTYPE" in
  darwin*) ;;
  *) echo -e "${RED}[ERROR]${NC} macOS only: $OSTYPE"; exit 1 ;;
esac

if [ ! -d "$EMACS_APP" ]; then
  echo -e "${RED}[ERROR]${NC} $EMACS_APP not found. Build it first."
  exit 1
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>              <string>Emacsclient</string>
  <key>CFBundleDisplayName</key>       <string>Emacsclient</string>
  <key>CFBundleIdentifier</key>        <string>dev.nathantebbs.emacsclient</string>
  <key>CFBundleVersion</key>           <string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key>       <string>APPL</string>
  <key>CFBundleExecutable</key>        <string>emacsclient-launcher</string>
  <key>CFBundleIconFile</key>          <string>Emacs.icns</string>
  <key>LSUIElement</key>               <true/>
  <key>NSHighResolutionCapable</key>   <true/>
</dict>
</plist>
PLIST

# LSUIElement keeps the launcher out of the Dock and the app switcher. The
# script exits as soon as the frame is up, so a Dock tile would only flicker.
cat > "$APP/Contents/MacOS/emacsclient-launcher" <<LAUNCHER
#!/bin/sh
# Generated by util/scripts/make-emacsclient-app.sh. Edit that, not this.
CLIENT="$EMACS_APP/Contents/MacOS/bin/emacsclient"

open_frame() {
  "\$CLIENT" -c -n "\$@" 2>/dev/null
}

if open_frame "\$@"; then
  exit 0
fi

# No socket. Hand it back to launchd rather than starting a stray daemon.
launchctl kickstart "gui/\$(id -u)/$LABEL" >/dev/null 2>&1 \\
  || launchctl bootstrap "gui/\$(id -u)" \\
       "\$HOME/Library/LaunchAgents/$LABEL.plist" >/dev/null 2>&1

# The daemon needs a moment to create the socket before a client can attach.
i=0
while [ \$i -lt 50 ]; do
  open_frame "\$@" && exit 0
  sleep 0.2
  i=\$((i + 1))
done

osascript -e 'display alert "Emacs daemon unavailable" message "launchctl could not start dev.nathantebbs.emacs. Check ~/Library/Logs/emacs-daemon.err."'
exit 1
LAUNCHER

chmod +x "$APP/Contents/MacOS/emacsclient-launcher"

ICON="$EMACS_APP/Contents/Resources/Emacs.icns"
if [ -f "$ICON" ]; then
  cp "$ICON" "$APP/Contents/Resources/Emacs.icns"
  echo -e "${GREEN}[OK]${NC} Icon taken from Emacs.app"
else
  echo -e "${YELLOW}[INFO]${NC} No Emacs.icns found; the bundle gets the generic icon"
fi

# Without this the bundle can take minutes to show up in Spotlight.
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
[ -x "$LSREGISTER" ] && "$LSREGISTER" -f "$APP"

echo -e "${GREEN}[OK]${NC} Built $APP"
