# Tmux Configuration
# Author: Nathan Tebbs

setw -g mode-keys vi

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Copy mode bindings (prefix + [ to enter, v to select, y to yank)
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# # Status bar
# set -g status-justify left
# set -g status-left " [#S] "
# set -g status-right " %H:%M %d-%b "
# set -g status-right-length 20
# set -g window-status-format " #I:#W "
# set -g window-status-current-format " #I:#W "
